// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltnuzzctjcyifxgtlyvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0bnV6emN0amN5aWZ4Z3RseXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODM3NzgsImV4cCI6MjA3Mzc1OTc3OH0.X1uVZtee_JxgYRUKCrB9AVKxYJGrmQBuP37hA2OXpqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});